### ISSUE TITLE
Stopped working in iOS 16.1 dev beta 1

### ISSUE THREAD

**Issue by krissen** [bigfoott/PoGOEvents#2]
At least, I didn't notice it not working prior to iOS 16.1 dev beta 1. 

Worked fine previously; now the widget is just empty. ![image](https://user-images.githubusercontent.com/2943684/190841860-6a8a5e06-ef5a-4dae-81c9-02ec7f6b7375.jpeg)

Have tried
- updating to latest release
- rebooting
- adding new widget
- running within Scriptable; nothing seemingly happens (other scripts do work); there's nothing in the log either 
![image](https://user-images.githubusercontent.com/2943684/190841921-4526b366-76e6-479a-bc82-d5f837cf7216.png)

**Comment by bigfoott** [comment]
Hi! I'm not currently able to update to 16.1 yet, but I believe this is a Scriptable issue.

Someone else is running into widget issues as well [on reddit](https://www.reddit.com/r/Scriptable/comments/xg50j9/ipados_161_some_scripts_works_in_app_but_not_as/), and the 1.16 beta version of Scriptable hasn't been released as a full update yet. I'm not sure if this is something I can fix until the app 
update is released.

**Comment by bigfoott** [comment]
Just wanted to update ya real quick: this seems like its actually a iOS 16.1 beta bug, rather than a Scriptable bug:

https://twitter.com/ibanks_x3/status/1572344748219990016

I guess keep an eye out on 16.1 beta pushes and see if any mention widget fixes :)

**Comment by krissen** [comment]
For the record, iOS 16.1 dev beta 2 did not fix it.

**Comment by HandaTakuya** [comment]
Found this problem as well in macOS Ventura Public Beta 5 and Beta 6

![Screenshot 2565-09-26 at 17 56 08](https://user-images.githubusercontent.com/47761725/192259583-06793c34-cead-47dc-b48c-933ac6b9e57f.png)

**Comment by bigfoott** [comment]
Hi! Looks like this was fixed in the latest 16.1 beta :)

The issue: https://twitter.com/simonbs/status/1577341212138389513

Scriptable dev saying it's been fixed: https://twitter.com/simonbs/status/1578463830258388997

**Comment by krissen** [comment]
It does indeed; can confirm. 👍
